// flow-typed signature: 2cfcce160200116d7464b7ad59b251eb
// flow-typed version: <<STUB>>/ansi-regex_v2.1.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ansi-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ansi-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ansi-regex/index' {
  declare module.exports: $Exports<'ansi-regex'>;
}
declare module 'ansi-regex/index.js' {
  declare module.exports: $Exports<'ansi-regex'>;
}
