// flow-typed signature: d7494fabdf5954ecc1b3c2c911b12e31
// flow-typed version: <<STUB>>/babel-preset-lux_v2.0.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-lux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-lux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-lux/index' {
  declare module.exports: $Exports<'babel-preset-lux'>;
}
declare module 'babel-preset-lux/index.js' {
  declare module.exports: $Exports<'babel-preset-lux'>;
}
