// flow-typed signature: 931b38e6c801fcb5516f8c19990c470b
// flow-typed version: <<STUB>>/babel-preset-lux_v1.3.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-lux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-lux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-lux/index' {
  declare module.exports: $Exports<'babel-preset-lux'>;
}
declare module 'babel-preset-lux/index.js' {
  declare module.exports: $Exports<'babel-preset-lux'>;
}
