// flow-typed signature: e5cc8b59627e541077987e5448a2d2a8
// flow-typed version: <<STUB>>/babel-plugin-istanbul_v2.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-istanbul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-istanbul/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-istanbul/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-istanbul/lib/index'>;
}
