// flow-typed signature: 4b00291a429acb5009c0e635c612b7da
// flow-typed version: <<STUB>>/inflection_v1.10.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inflection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inflection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inflection/inflection.min' {
  declare module.exports: any;
}

declare module 'inflection/lib/inflection' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inflection/inflection.min.js' {
  declare module.exports: $Exports<'inflection/inflection.min'>;
}
declare module 'inflection/lib/inflection.js' {
  declare module.exports: $Exports<'inflection/lib/inflection'>;
}
