// flow-typed signature: 5eabb9d39c7bd8ce0a65b0e21b41d991
// flow-typed version: <<STUB>>/inflection_v1.12.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inflection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inflection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inflection/inflection.min' {
  declare module.exports: any;
}

declare module 'inflection/lib/inflection' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inflection/inflection.min.js' {
  declare module.exports: $Exports<'inflection/inflection.min'>;
}
declare module 'inflection/lib/inflection.js' {
  declare module.exports: $Exports<'inflection/lib/inflection'>;
}
