// flow-typed signature: 047070d67812005361f8353411215c23
// flow-typed version: <<STUB>>/rollup-plugin-multi-entry_v2.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-multi-entry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-multi-entry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-multi-entry/dist/rollup-plugin-multi-entry' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-multi-entry/dist/rollup-plugin-multi-entry.js' {
  declare module.exports: $Exports<'rollup-plugin-multi-entry/dist/rollup-plugin-multi-entry'>;
}
