// flow-typed signature: 08b63102f9d84900bbfc2fb4066d1b08
// flow-typed version: <<STUB>>/rollup-plugin-lux_v3.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-lux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-lux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-lux/decl/acorn' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/decl/eol' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/decl/magic-string' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/dist/index.es' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/dist/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/acorn_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/babel-plugin-transform-es2015-modules-commonjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/eol_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/eslint-config-airbnb-base_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/fs-promise_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/jest_v18.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/jest-junit_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/magic-string_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/remark-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/remark-preset-lint-recommended_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/rollup_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/rollup-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/flow-typed/npm/shx_vx.x.x' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/rollup.config' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/src/constants' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/src/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/src/interfaces' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/src/transform/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/src/transform/interfaces' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/src/transform/parse-source' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/src/transform/render' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/src/transform/static-name' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/src/utils/compose' {
  declare module.exports: any;
}

declare module 'rollup-plugin-lux/src/utils/test/compose.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-lux/decl/acorn.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/decl/acorn'>;
}
declare module 'rollup-plugin-lux/decl/eol.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/decl/eol'>;
}
declare module 'rollup-plugin-lux/decl/magic-string.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/decl/magic-string'>;
}
declare module 'rollup-plugin-lux/dist/index.es.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/dist/index.es'>;
}
declare module 'rollup-plugin-lux/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/dist/index'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/acorn_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/acorn_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/babel-plugin-transform-es2015-modules-commonjs_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/babel-plugin-transform-es2015-modules-commonjs_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/eol_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/eol_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/eslint-config-airbnb-base_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/eslint-config-airbnb-base_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/fs-promise_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/fs-promise_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/jest_v18.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/jest_v18.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/jest-junit_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/jest-junit_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/magic-string_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/magic-string_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/remark-cli_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/remark-cli_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/remark-preset-lint-recommended_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/remark-preset-lint-recommended_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/rollup_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/rollup_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/rollup-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/rollup-plugin-babel_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x'>;
}
declare module 'rollup-plugin-lux/flow-typed/npm/shx_vx.x.x.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/flow-typed/npm/shx_vx.x.x'>;
}
declare module 'rollup-plugin-lux/rollup.config.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/rollup.config'>;
}
declare module 'rollup-plugin-lux/src/constants.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/src/constants'>;
}
declare module 'rollup-plugin-lux/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/src/index'>;
}
declare module 'rollup-plugin-lux/src/interfaces.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/src/interfaces'>;
}
declare module 'rollup-plugin-lux/src/transform/index.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/src/transform/index'>;
}
declare module 'rollup-plugin-lux/src/transform/interfaces.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/src/transform/interfaces'>;
}
declare module 'rollup-plugin-lux/src/transform/parse-source.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/src/transform/parse-source'>;
}
declare module 'rollup-plugin-lux/src/transform/render.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/src/transform/render'>;
}
declare module 'rollup-plugin-lux/src/transform/static-name.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/src/transform/static-name'>;
}
declare module 'rollup-plugin-lux/src/utils/compose.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/src/utils/compose'>;
}
declare module 'rollup-plugin-lux/src/utils/test/compose.test.js' {
  declare module.exports: $Exports<'rollup-plugin-lux/src/utils/test/compose.test'>;
}
