// flow-typed signature: 1bf551e5f6fd16009f418a19ac551ca4
// flow-typed version: <<STUB>>/rollup-plugin-cleanup_v1.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-cleanup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-cleanup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-cleanup/dist/rollup-plugin-cleanup.es' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/dist/rollup-plugin-cleanup' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/blank-comments' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/cleanup' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/parse-options' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/remove-lines' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/util/filter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-cleanup/dist/rollup-plugin-cleanup.es.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/dist/rollup-plugin-cleanup.es'>;
}
declare module 'rollup-plugin-cleanup/dist/rollup-plugin-cleanup.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/dist/rollup-plugin-cleanup'>;
}
declare module 'rollup-plugin-cleanup/src/blank-comments.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/blank-comments'>;
}
declare module 'rollup-plugin-cleanup/src/cleanup.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/cleanup'>;
}
declare module 'rollup-plugin-cleanup/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/index'>;
}
declare module 'rollup-plugin-cleanup/src/parse-options.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/parse-options'>;
}
declare module 'rollup-plugin-cleanup/src/remove-lines.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/remove-lines'>;
}
declare module 'rollup-plugin-cleanup/src/util/filter.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/util/filter'>;
}
