// flow-typed signature: eee8737f140fb2181901ea9484928216
// flow-typed version: <<STUB>>/rollup-plugin-alias_vzacharygolba/rollup-plugin-alias#feat-resolve-index/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-alias/src/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-alias/test/files/aliasMe' {
  declare module.exports: any;
}

declare module 'rollup-plugin-alias/test/files/folder/anotherNumber' {
  declare module.exports: any;
}

declare module 'rollup-plugin-alias/test/files/folder/hipster' {
  declare module.exports: any;
}

declare module 'rollup-plugin-alias/test/files/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-alias/test/files/localAliasMe' {
  declare module.exports: any;
}

declare module 'rollup-plugin-alias/test/files/nonAliased' {
  declare module.exports: any;
}

declare module 'rollup-plugin-alias/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-alias/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-alias/src/index'>;
}
declare module 'rollup-plugin-alias/test/files/aliasMe.js' {
  declare module.exports: $Exports<'rollup-plugin-alias/test/files/aliasMe'>;
}
declare module 'rollup-plugin-alias/test/files/folder/anotherNumber.js' {
  declare module.exports: $Exports<'rollup-plugin-alias/test/files/folder/anotherNumber'>;
}
declare module 'rollup-plugin-alias/test/files/folder/hipster.jsx' {
  declare module.exports: $Exports<'rollup-plugin-alias/test/files/folder/hipster'>;
}
declare module 'rollup-plugin-alias/test/files/index.js' {
  declare module.exports: $Exports<'rollup-plugin-alias/test/files/index'>;
}
declare module 'rollup-plugin-alias/test/files/localAliasMe.js' {
  declare module.exports: $Exports<'rollup-plugin-alias/test/files/localAliasMe'>;
}
declare module 'rollup-plugin-alias/test/files/nonAliased.js' {
  declare module.exports: $Exports<'rollup-plugin-alias/test/files/nonAliased'>;
}
declare module 'rollup-plugin-alias/test/index.js' {
  declare module.exports: $Exports<'rollup-plugin-alias/test/index'>;
}
